version: "2"
services:
  web:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - mongo
  mongo:
    image: mongo
    volumes:
    - ./mongo-volume:/data/db
    ports:
    - "27017:27017"


    